"""Initial database schema

Revision ID: bc0f0b03d099
Revises: 
Create Date: 2026-02-25 14:26:44.239405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0f0b03d099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_exposure',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('admin_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('last_administered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('self_assess', sa.String(length=20), nullable=False),
    sa.Column('exam_experience', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('initial_theta', sa.Float(), nullable=False),
    sa.Column('final_theta', sa.Float(), nullable=True),
    sa.Column('final_se', sa.Float(), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('cefr_level', sa.String(length=5), nullable=True),
    sa.Column('cefr_probabilities', sa.JSON(), nullable=True),
    sa.Column('curriculum_level', sa.String(length=50), nullable=True),
    sa.Column('vocab_size_estimate', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_correct', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('termination_reason', sa.String(length=50), nullable=True),
    sa.Column('topic_strengths', sa.JSON(), nullable=True),
    sa.Column('topic_weaknesses', sa.JSON(), nullable=True),
    sa.Column('dimension_scores', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('question_type', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_dont_know', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('theta_before', sa.Float(), nullable=False),
    sa.Column('theta_after', sa.Float(), nullable=False),
    sa.Column('se_before', sa.Float(), nullable=False),
    sa.Column('se_after', sa.Float(), nullable=False),
    sa.Column('difficulty_b', sa.Float(), nullable=False),
    sa.Column('discrimination_a', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('test_sessions')
    op.drop_table('users')
    op.drop_table('item_exposure')
    # ### end Alembic commands ###
